export enum Subjects {
  CollectionCreate = "collection:created",
  CollectionUpdate = "collection:updated",
  ItemCreate = "item:created",
  ItemUpdate = "item:updated",
  UserCreateAvax = "user:created:avax",
  UserUpdateAvax = "user:updated:avax",
  UserCreateEth = "user:created:eth",
  UserUpdateEth = "user:updated:eth",
  UserCreateBnb = "user:created:bnb",
  UserUpdateBnb = "user:updated:bnb",
  UserCreatePolygon = "user:created:polygon",
  UserUpdatePolygon = "user:updated:polygon",
  UserCreate = "user:created",
}
