export const Projects = [
  {
    id: 0,
    name: "Project 1",
    description: "Project 1 description",
    image: "",
    status: "open",
    currency: "busd",
    swap_rate: "xxxx",
    cap: "xxxx",
    access: "xxxx",
    progress: "5",
    participants: "0",
    website: "https://www.google.com",
    twitter: "https://www.google.com",
    telegram: "https://www.google.com",
  },
  {
    id: 1,
    name: "Project 2",
    description: "Project 2 description",
    image: "",
    status: "upcoming",
    currency: "busd",
    swap_rate: "xxxx",
    cap: "xxxx",
    access: "xxxx",
    progress: "5",
    participants: "0",
    website: "https://www.google.com",
    twitter: "https://www.google.com",
    telegram: "https://www.google.com",
  },
  {
    id: 2,
    name: "Project 3",
    description: "Project 3 description",
    image: "",
    status: "closed",
    currency: "busd",
    swap_rate: "xxxx",
    cap: "xxxx",
    access: "xxxx",
    progress: "5",
    participants: "0",
    website: "https://www.google.com",
    twitter: "https://www.google.com",
    telegram: "https://www.google.com",
  },
];
